// sssihms-achievements.jsx — the departmental academic record.
// Source: /anes-achievements/ on the live site (9,418 words, 491 entries).
// The design pass had reduced this page to three summary cards; the full record
// is restored here behind the 'achievements' section type, which groups entries,
// pulls each one's year out into a chip, and collapses each group so the page
// stays navigable instead of running to 9,000 words of flat list.
(function(){
const PAGES = window.PAGES;

PAGES['anes-achievements'] = {
  title:'Achievements \u2014 Anesthesiology', crumb:'Departments \u00b7 Anesthesiology \u00b7 Achievements', subnav:'anesthesiology',
  subtitle:'Quiet excellence behind three thousand surgeries a year \u2014 the department\u2019s teaching, research and academic record.',
  sections:[
    { type:'cards', eyebrow:'Recognition', title:'Contributions', cols:3, items:[
      { title:'Cardiac Anaesthesia Fellowship', desc:'An 18-month FNB-level Cardiothoracic & Vascular Anaesthesia fellowship covering adult and paediatric cardiac anaesthesia, TEE and intensive care.' },
      { title:'Academic Roles', desc:'Faculty serve as examiners, deliver lectures at national conferences and contribute to research and peer review.' },
      { title:'Teaching Through Telemedicine', desc:'Online CMEs and DNB teaching sessions conducted through the Sri Sathya Sai Telemedicine network.' }
    ] },
    { type:'achievements', eyebrow:'Academic Record', title:'Teaching, Research & Recognition',
      sub:'Four hundred and ninety-one entries, grouped as the department records them. Open a group to read it.',
      openFirst:true,
      groups:[
        { title:"Workshops & Conferences", count:16,
          entries:[
            {"text": "Kolli S. Chalam chaired a session for awake cardiac surgeries under thoracic Epidurals’ at PG ex-cel post graduate CME organized by Bangalore Medical College, Bangalore on 12th June 2009.", "year": "2009"},
            {"text": "Kolli S. Chalam chaired a session on ARDS, at Critical care workshop, Narayana Hrudayalaya medical sciences, August 6-8. 2010, Bangalore.", "year": "2010"},
            {"text": "Sunil Chhajwani chaired a session and presented ‘US guided IJV cannulation’ at Critical care work shop organized by NH, August 6-8. 2010, Bangalore.", "year": "2010"},
            {"text": "Kolli S. Chalam Chaired for ‘Pulse contour as means to measure cardiac output – Dr. Rakhee Balachandran’. & “Esophageal Doppler for cardiac output – Dr. Ravi Baikady at 14th National conference of Indian Association of Cardiovascular Thoracic Anaesthesiologists (IACTA)-2011.BANGALURU, INDIA ,18th to 20th Feb 2011.", "year": "2011"},
            {"text": "Kolli S. Chalam Chaired for Plenary Lectures entitled “Anaesthesiologists role in peri-operative lung protection Dr. Peter Slinger, Professor of Anesthesia, Univ of Toronto, at National Conference of the Research Society of Anaesthesiology and Clinical Pharmacology 23 & 24 October 2010.", "year": "2010"},
            {"text": "Kolli S. Chalam Chaired a session entitled ‘Epicardial / epiaortic TEE-Dr. Nilesh M Juvekar and Patient prosthetic mismatch’ Dr. Alexander Dewhurst. at 5th National TEE Workshop at NH, Bangalore;23rd to 25th August 2011, pre conference work shop of SAARC.", "year": "2011"},
            {"text": "Kolli S. Chalam Chaired sessions entitled ‘Anaesthesia for beating heart bypass surgery’ by Dr Murali Chakravarthy. Date: 26/08/2011 SAARC conference, 25 August 2011, Bangalore.", "year": "2011"},
            {"text": "Kolli S. Chalam chaired a session on Pediatric Anesthesia and also served as jury for free paper session at INDIAN SOCIETY of ANESTHESIOLOGISTS (South Zone) at Coimbatore. CASCO2012’ 11-12 August 2012.", "year": "2012"},
            {"text": "Kolli S. Chalam chaired a session on “sepsis surviving guidelines”. at Bangalore Medical College and Research Institution, anaesthesia 2012” CME on “Critical Care: concepts to practice”.", "year": "2012"},
            {"text": "Anaesthesia Department hosted the scientific session of city branch of ISCCM for the month of May 2013 at Atria Hotel with moderator: Dr Kolli S. Chalam.", "year": "2013"},
            {"text": "Kolli S. Chalam as faculty as Chairman at 7th National IACTA-TEE Workshop in collaboration with Indian Academy of Echocardiography (IAE), University of Minnesota, USA & International Society of Cardiovascular Ultrasound (ISCU) held at Narayana Hrudayalaya, Bangalore, from 2nd to 5th of September 2013.", "year": "2013"},
            {"text": "Chaired a session at 8th National & 3rd International Transesophageal Echocardiography (TEE) conference at August 2014 at Narayana Hrudayalaya , Bangalore", "year": "2014"},
            {"text": "Chaired a session at 9th National & 3rd International Transesophageal Echocardiography (TEE) conference at August 2015 at Narayana Hrudayalaya , Bangalore", "year": "2015"},
            {"text": "Chaired a session at 10th National & 3rd International Transesophageal Echocardiography (TEE) conference at August 2016 at Narayana Hrudayalaya , Bangalore", "year": "2016"},
            {"text": "Chaired a session at 11th National & 3rd International Transesophageal Echocardiography (TEE) conference at August 2017 at Narayana Hrudayalaya , Bangalore", "year": "2017"},
            {"text": "Kolli S. Chalam as faculty chaired a session at 12th National & 3rd International Transesophageal Echocardiography (TEE) conference at August 2018 at Narayana Hrudayalaya, Bangalore.", "year": "2018"},
          ],
        },
        { title:"Lectures Delivered & Scientific Papers Presented", count:73,
          entries:[
            {"text": "Kolli S. Chalam participated in panel discussion on TBI, ICP management at Critical care Medicine update 2009: SSSIHMS, Whitefield, Bangalore:", "year": "2009"},
            {"text": "Kolli S. Chalam delivered a lecture on Anesthetic considerations of Phygo-phagus conjoined Twins’ surgeries: at annual conference of Indian society of Anesthesiologists at Jodhpur, Rajasthan Dec ember’ 2009.", "year": "2009"},
            {"text": "Kolli S. Chalam delivered a lecture as guest faculty on Poly-trauma and Critical care: BAPU, SVIMS, Tirupathi, AP; Sept’6 2009.", "year": "2009"},
            {"text": "SunilChhajwani lectured on the role of intraoperative TEE at Critical care Medicine update 2009: SSSIHMS, Whitefield, Bangalore.", "year": "2009"},
            {"text": "Kolli S. Chalam delivered a lecture as guest faculty on ‘Anesthetic management of Necrotising enterocolitis’ RACE, Ramachandra University, Chennai, February 2010.", "year": "2010"},
            {"text": "Kolli S. Chalam delivered a lecture on ‘Critical care obstetrics: Critical care medicine update’ 2010: International conference with the joint participation of university of Cincinnati, USA 29th May 2010.", "year": "2010"},
            {"text": "Kolli S. Chalam delivered a lecture entitled Anesthetic review of Paediatric Neuro surgeries 1087 cases at SSSIHMS, Whitefield, ISA , Bangalore chapter; May 30, 2011.", "year": "2011"},
            {"text": "Aurita Kamat lectured on Anesthetic review of 120 patients of Myasthenia Gravis: at SSSIHMS, Whitefield, ISA, Bangalore chapter; May 30, 2011.", "year": "2011"},
            {"text": "Sunil Chhajwani delivered a talk on Anaesthetic management of ALCAPA at SSSIHMS, Whitefield, ISA, Bangalore chapter; May 30, 2011.", "year": "2011"},
            {"text": "Kolli S. Chalam delivered a lecture on ‘Ventilator Associated Pneumonia’ lecture at Indian Society of Anaesthesiologists (South Zone) at Coimbatore CASCO2012 on 11-12 August 2012.", "year": "2012"},
            {"text": "Kolli S. Chalam delivered a lecture on practical Sedation and Anaesthesia techniques for Cardiac CT and MRI at RADILOGY conference hosted by DEPT. of SSSIHMS, WFD on behalf of Indian Association of Cardiac Imaging 1-2 Dec 2012.", "year": "2012"},
            {"text": "Dr Sathya Swaroop Patnaik presented a paper on Comparison of Epidural Bupivacaine versus Bupivacaine and Butorphanol in Global Update on Pain 2012 at Mumbai- Awarded 2nd place", "year": "2012"},
            {"text": "Kolli S. Chalam delivered guest lecturer at ISNACC2012 at Varanasi on Anaesthesia and Neuro critical care for High Risk cardiac patients undergoing Neuro surgeries on 9th Feb 2013.BHU, Varanasi", "year": "2013"},
            {"text": "Kolli S. Chalam as invited faculty conducted Case Discussion: Bangalore exam 0riented anaesthesia training programme (BE-ORATE), Sri Govindswamy centre, NIMHANS campus, Bangalore day 1 ~ 8th March 2013.", "year": "2013"},
            {"text": "Dr Sunil Chhajwani lectured on Lung USG: A new tool to predict cardiac filling pressures, PVR and EVLW – at ISCCM, Atria Hotel, on 29th May 2013.", "year": "2013"},
            {"text": "Dr Pankaj Punetha gave a lecture on Neuro-Critical Care: concerns of acromegaly undergoing pituitary surgery, at ISCCM, Atria Hotel on 29th May 2013.", "year": "2013"},
            {"text": "Satya Swaroop Patnaik gave a lecture on Cardiac Intensive care management of multi-organ dysfunction in a post-operative VSD closure surgery patient following MI; at ISCCM on 29th May 2013", "year": "2013"},
            {"text": "Dr Sathya Swaroop Patnaik presented a poster on Anesthetic management of patient with sickle cell anaemia for ASD closure in IACTA 2013 at Kochi.", "year": "2013"},
            {"text": "Kolli S. Chalam delivered a lecture on Anaesthetic management of IHD patient posted for ORIF fracture FEMUR at PG EXCEL 2013, Conducted by ESIC PGIMSR, Rajaji Nagar, Bangalore, in collaboration with City Branch, ISA, Bangalore, on 10/08/2013.", "year": "2013"},
            {"text": "Dr Sunil Chhajwani lectured on Vascular access using USG at 7th National IACTA-TEE Workshop in collaboration with Indian Academy of Echocardiography (IAE), University of Minnesota, USA & International Society of Cardiovascular Ultrasound (ISCU) held at Narayana Hrudayalaya, Bangalore, from 2—5th of September 2013", "year": "2013"},
            {"text": "Kolli S. Chalam delivered Guest Lecture on “Newer Drugs in anaesthesia: an update on 14th Sept 2013 at KISACON 2013; (Karnataka State Conference of Indian Society of Anaesthesiologists), at RAJA RAJESWARI MEDICAL COLLEGE AND HOSPITAL BANGALORE.", "year": "2013"},
            {"text": "Dr Kolli S. Chalam delivered a Lecture at PGEXCEL2014 at Siddartha Medical College, Tumkur, titled Anaesthesia for the Patient with Pacemaker for Non Cardiac Surgery, on 10/08/2014.", "year": "2014"},
            {"text": "Dr Kolli S. Chalam delivered a Lecture for KOPS Award presentation during the 62nd Annual National Conference of Indian Society of Anaesthesiologists on 25th Dec 2014 in the Temple City of Madurai, on Anaesthetic management of atrial myxomas.", "year": "2014"},
            {"text": "Sriranga Joshi presnted a poster on LA Myxoma patient with cardiogenic shock in IACTA 2015 at Jaipur.", "year": "2015"},
            {"text": "Pankaj Punetha delivered a lecture at Apollo Hospital on CME on Paediatric Anaesthesia conducted by Apollo Hospitals on 19 July 2015. Topic –Anaesthesia for Paediatric Neurosurgical Procedures.", "year": "2015"},
            {"text": "Kolli S. Chalam (i) Attended as Guest Faculty in the scientific committee of ISACON2015 of Indian society of Anaesthesiologists (national conference) held during 27-28th Dec 2015. Jaipur.", "year": "2015"},
            {"text": "Presented a scientific paper titled \" Pediatric Difficult airway: current devices & techniques and also as a panelist at panel discussion titled “Delayed post-anesthesia recovery”."},
            {"text": "ii) 2015 AHA Guidelines for CPR and Emergency Cardiovascular Care International Instructor Update November 21, 2015 at The Hyderabad International Convention Center. Hyderabad.", "year": "2015"},
            {"text": "Kolli S. Chalam deliverede a lecture at CACME (Cardiac Anaesthesia CME) Sri Jayadeva institute of cardiovascular sciences and research, Bangalore on 18th sept 2016 on “Importance of risk assessment scores”", "year": "2016"},
            {"text": "Pankaj Punetha attended 2015 AHA Guidelines for CPR and Emergency Cardiovascular Care International Instructor Update November 21, 2015 at the Hyderabad International Convention Centre. Hyderabad", "year": "2015"},
            {"text": "Pankaj Punetha attended “Emergency Neurological Life Support Course (ENLS) A 1-day training course on 'Emergency Neurological Life Support” was successfully conducted by the faculty from Neurocritical Care Society of US, as a pre-conference workshop on 04 February 2016", "year": "2016"},
            {"text": "Anuradha Kamath Pcsi Bangalore 2016 Delayed Chest Closure In Congenital Heart Surgery …..Challenging Yet Satisfying", "year": "2016"},
            {"text": "Pankaj Punetha attended as Faculty – Judged the Poster presentation in ISNACC 2016 held from 5th to 7th February 2016 at NIMHANS Convention Centre, Bangalore", "year": "2016"},
            {"text": "Kolli S. Chalam delivered lecture on Anaesthesia concerns of Heart Transplantation, RAJA RAJESWARI MEDICAL COLLEGE AND HOSPITAL BANGALORE to mark the World Anaesthesia day on 16TH Oct 2016.", "year": "2016"},
            {"text": "Kolli S. Chalam delivered lecture on Anaesthesia workstation Andhra Medical college Visakhapatnam March 2017", "year": "2017"},
            {"text": "Dr Pankaj Punetha received the medal for “Best Student” of Diploma in Hospital Management (2015-16) conducted by the National Institute of Health and Family Welfare (Autonomous organization under the Ministry of Health and Family Welfare) on 9th March 2017 during the Annual day function of NIHFW at New Delhi. .", "year": "2017"},
            {"text": "Kolli S. Chalam carried “CVP video presentation at CME of KISACON 2017”,VIMS Medical college Bellary, August 2017", "year": "2017"},
            {"text": "Kolli S. Chalam, Lecture on tropical Fevers with MODF at IDCCM refresher course conducted by Indian Society of Critical Care, Bangalore September 2017", "year": "2017"},
            {"text": "Kolli S. Chalam, Lecture on Ambulatory Anaesthesia at APISACON 2017, Rangaraya Medical College, Kakinada ,Andhra Pradesh", "year": "2017"},
            {"text": "Kolli S. Chalam, a lecture on Sepsis at BICS, Bangalore intensive care society, Bangalore November 2017.", "year": "2017"},
            {"text": "Anitha Diwakar, -Rupture of sinus of valsalva- A 15year’s single institutional retrospective review,IACTA Pune ,February 2017.", "year": "2017"},
            {"text": "Anitha Diwakar Review of 25 cases of doubly committed VSDintraoperative echocardiographic diagnosis and implications. IACTA Pune, February 2017.", "year": "2017"},
            {"text": "Anitha DiwakarLarge PDA feeding the descending aorta leading to miss the diagnosis of coarctation by transoesophageal echocardiography in a rare case of anatomically corrected malposition of great arteries, IACTA Pune ,Feb 2017.", "year": "2017"},
            {"text": "Anitha Diwakar, Comparison of outcomes of two techniques in Tetralogy of Fallot with Doubly Committed ventricular septal defect. IACTA Pune, Feb 2017.", "year": "2017"},
            {"text": "Anitha Diwakar Acute recurrent left pulmonary artery thrombosisfollowing intracardiac repair of Tetralogy of Fallot, IACTA Pune ,Feb 2017.", "year": "2017"},
            {"text": "Anitha Diwakar paper presented at Chennai Cardiac Update November 2017:Aorta -LV tunnel Post Cardiac surgery renal dysfunction.", "year": "2017"},
            {"text": "Anuradha Kamath Delivered “Aberrant Tracheal Bronchus With Tracheal Stenosis In Tapvc- A First – In –Literature Post Operative Nightmare !!” , Submission For Oral Presentation – Iacta 2017", "year": "2017"},
            {"text": "Anuradha Kamath , Delivered “Where Nature Played Truant….!! Embolising Mapcas In Post- Operative Sennings Patient :” IACTA 2017", "year": "2017"},
            {"text": "Anuradha Kamath Delayed Chest Closure In Congenital Heart Surgery"},
            {"text": "…..Challenging Yet Satisfying!!!...Iacta 2017.", "year": "2017"},
            {"text": "54.Dr.Anuradha Kamath comduc ted workshop SCORE 2017 , topic POST OP ICU CARE, 2017", "year": "2017"},
            {"text": "Dr.Anitha Diwakar conducted workshop SCORE 2017 , POST OP ICU , 2017", "year": "2017"},
            {"text": "Dr, Anuradha Kamath conducted workshop SCORE 2018 , topic “ICU CASE SCENERIO”, 2018", "year": "2018"},
            {"text": "Dr.Anitha Diwakar conducted workshop SCORE 2018 , topic “ICU CASE SCENERIO “2018", "year": "2018"},
            {"text": "Dr.Anitha Diwakar delivered lecture ICU care for paediatric cardiac surgery, MACS2017, Jaipur, Rajasthan."},
            {"text": "Kolli S. Chalam, “Clinical update: Perioperative Glycaemia control in cardiac surgery – Do we have a target yet?” 2nd National Symposium on Cardiac Surgical Critical Care - 22 to 24 June 2018, Institute of Cardio-Vascular Diseases,The Madras Medical Mission ,No.4-A, Dr. J.J. Nagar, Mogappair, Chennai 600037,India.", "year": "2018"},
            {"text": ".Dr Kolli S. Chalam, Troubleshooting versus Problem Solving at National mechanical ventilation workshop, 2018, conducted at Narayana Hrudayalaya , Bengaluru.", "year": "2018"},
            {"text": "Kolli S. Chalam Physical principles of vaporisers on 26th January 2018 at Vydehi Institute of Medical Sciences and Research Centre In association with Bangalore City Branch of Indian Society of Anaesthesiologists", "year": "2018"},
            {"text": "Anuradha Kamath Airway Anomalies In Patients With Anomalous Pulmonary Venous Drainage- Three Rare Cases With Literature Review, Iacta2018"},
            {"text": "Anuradha Kamath.Lectures delivered on “Complex Congenital Heart Disease for Non Cardiac Surgery Anaesthesia considerations “, at ISACON 2018, Kerala", "year": "2018"},
            {"text": "Anuradha Kamath Paper presentation on “Anaesthetic Management of Idiopathic LV APICAL Aneurysm with severe LV Dysfunction & Recurrent VT – TEE & Foleys Catheter to the Rescue. presented at IACTA 2018 , Hyderabad", "year": "2018"},
            {"text": "Kolli S. Chalam, Faculty for the FCCS (Fundamental Critical Care Support) - Obstetric Course being held at Hyderabad on 9th and 10th Jan 2019 at Century Hospital, Hyderabad.", "year": "2019"},
            {"text": "Kolli S. Chalam, Lecture on “NMBA's and reversal agents\" at 2nd Annual CME, ACME 2019 on 20th January 2019 (Sunday) at VIMS, Bengaluru.", "year": "2019"},
            {"text": "Kolli S. Chalam, : Faculty for a case discussion at P-G Excel at Raja Rajeswari Medical College & Hospital on FEB 9 & 10, 2019, Bengaluru.", "year": "2019"},
            {"text": "Kolli S. Chalam, Lectures on i) Thesis protocol writing ii) Citing & Referencing (Vancouver Style) & Basics of Zotero iii) Publication of clinical research at the CME of research methodology of NBE on 16-02-2019 & 17-02-2019", "year": "2019"},
            {"text": "Kolli S. Chalam, Faculty for case discussion and viva stations at BEORATE Mock exam, conducted by ISA, Bengaluru branch, 10th March 2019.", "year": "2019"},
            {"text": "Dr Pankaj Punetha attended the 2nd National Conference on Communication in Healthcare COMMUNICON 2019 held by National Board of Examinations at New Delhi on 6th and 7th April 2019.", "year": "2019"},
            {"text": "Dr Pankaj Punetha attended the 3rd NBE-UNESCO Post Graduate Certificate 3T-IBHSc course on 8th – 10th June 2019 at Narayana Health City, Bangalore", "year": "2019"},
            {"text": "Kolli S. Chalam, Faculty of National Mechanical Ventilation & Hemodynamic workshop held at Narayana Hrudayalya, Bangalore, in August 2019", "year": "2019"},
            {"text": "Kolli S. Chalam, Faculty of International Conference of Echocardiography organized at Narayana Hrudalaya Bangalore, in August 2019", "year": "2019"},
            {"text": "Kolli S. Chalam, Faculty for Hemodynamic Workshop dated 25th November 2019 for the topics “Overview of hemodynamic monitoring”, Physics and Principles of CVP monitoring”, “CVP monitoring”, “Hypovolemic or hemorrhagic shock”", "year": "2019"},
            {"text": "Kolli S. Chalam, Faculty in Sri Sathya Sai Medicare Conference and lectured on “Medical marvels- Sri Sathya Sai Super speciality hospitals” held at Sundaram Temple, Sri Sathya Sai Seva Organisation Tamilnadu, Chennai on 3rd November 2019", "year": "2019"},
            {"text": "Kolli S. Chalam, delivered a lecture on Sai Super Speciality hospitals at Sri Sathya Sai Medicare conference organised by Sri Sathya Sai SevaOrganisation , New Delhi on 15th December 2019 at Sri Sathya Sai International Centre New Delhi.", "year": "2019"},
          ],
        },
        { title:"Scientific Publications", count:32,
          entries:[
            {"text": "Kolli S. Chalam. Anesthetic Management of Conjoined Twins’ Separation Surgery. Indian Journal of Anaesthesia 2009; 53 (3):294-301.", "year": "2009"},
            {"text": "Ravi Dadlani,Kolli S. Chalam : Can bradycardia pose as a “red herring” in neurosurgery? Surgical stress exposes an asymptomatic sick sinus syndrome: Diagnostic and management dilemmas. Indian J Crit Care Med. 2010 Oct-Dec; 14(4): 212–216.", "year": "2010"},
            {"text": "Kolli S. Chalam, Inspiring Seva. 2006.http://media.radiosai.org/journals/Vol_04/01DEC06/06-AbuDhabi.htm Serve and Inspire SAI Seva in Abu Dhabi2006. http://media.radiosai.org/journals/Vol_04/01APR06/abu_dhabi_seva.htm", "year": "2006"},
            {"text": "Kolli S. Chalam, Noteworthy EHV Workshops in Abu Dhabi. http://media.radiosai.org/journals/Vol_05/01MAR07/15-worldnews.htm 2007.http://media.radiosai.org/journals/Archives/SaiWorldNews_Archives.htm", "year": "2007"},
            {"text": "Kolli S. Chalam, Poly-trauma and Critical care: BAPU, SVIMS, Tirupathi, 2009http://medind.nic.in/iad/t09/i4/iadt09i4p467.pdf"},
            {"text": "Kolli S. Chalam, Anaesthesia for premature neonate with NEC: RACE2010. http://www.sriramachandra.edu.in/anaesthesiology_conferences_organized.htm"},
            {"text": "Kolli S. Chalam, VENTILATOR ASSOCIATED PNEUMONIA (VAP) www.isakanyakumari.com/CASCO2012/Conf/III%25205%2520A.p"},
            {"text": "Kolli S. Chalam, Anaesthesia and neuro critical care of High risk cardiac patients undergoing neurosurgeries: ISNACC2013, CME session. http://www.isnacc.org/Synapse.pdf"},
            {"text": "Chalam KS A comparative study of intravenous dexmedetomidine-versus propofol-based sedation for awake Fiberoptic intubation along with airway blocks in cervical discectomy patients. Karnataka Anaesth J 2015; 1:21-7.", "year": "2015"},
            {"text": "Kolli S. Chalam, Patnaik SS, Sunil C, Bansal.T. Comparative study of ultrasound-guided paravertebral block with ropivacaine versus bupivacaine for post-operative pain relief in children undergoing thoracotomy for patent ductus arteriosus ligation surgery. Indian J Anaesth 2015; 59:493-", "year": "2015"},
            {"text": "Chalam KS, Gupta J. Comparison of intubating laryngeal mask airway and fiberoptic bronchoscopy for endotracheal intubation in patients undergoing cervical discectomy. J Anaesthesiol Clin Pharmacol 2016; 32:515-8.", "year": "2016"},
            {"text": "Malhotra A, Gupta V, Abraham M, Punetha P, Bundela Y. Quantifying the amount of bleeding and associated changes in intra-abdominal pressure and mean airway pressure in patients undergoing lumbar fixation surgeries: a comparison of three positioning systems. Asian spine journal. 2016 Apr; 10(2):199.", "year": "2016"},
            {"text": "Reddy PB, Punetha P, Chalam KSUltrasonography - A viable tool for airway assessment. Indian J Anaesth 2016; 60:807-13.", "year": "2016"},
            {"text": "Anuradha Kamath “Complex Congenital Heart Disease for Non Cardiac Surgery Anaesthesia considerations “, published in the book ISACON 2018, Kerala", "year": "2018"},
            {"text": "Anitha Diwakar1, Sathya Swaroop Patnaik 1, Kolli S. Chalam , Parvatkumar Dash , “Rupture of Sinus of Valsalva – A 15- year single Institutional Retrospective Review: Does Preoperative Heart Failure have an impact on Postoperative outcome? Ann Card Anaesth. Jan-Mar 2019; 22(1):24-29.", "year": "2019"},
            {"text": "Anuradha Kamath A, Punetha P, Doddamane AN, Chalam KS, Hiremath CS. Airway anomalies in cases of anomalous pulmonary venous connection–A single-center experience. Annals of Cardiac Anaesthesia. 2020 Jan; 23(1):14.", "year": "2020"},
            {"text": "MEMBERSHIPS"},
            {"text": "Kolli S. Chalam is the peer reviewer of Indian Journal of Anaesthesia since 2010.", "year": "2010"},
            {"text": "Kolli S. Chalam is on the panel of panel of examiners, panel for interview boards, and assigning examination, Nizams Institute of Medical Sciences (NIMS): Hyderabad."},
            {"text": "Member of International Anaesthesia Research Society under vide no. IARS 17949440 Ohio; USA."},
            {"text": "Life Member of Indian Society of Anaesthesiologists. C0555"},
            {"text": "Life Indian society of Critical care Medicine : 11/C-232"},
            {"text": "Life Indian association of cardiac- thoracic anaesthesiologists (IACTA). No. CLC/733"},
            {"text": "Member of Neurocritical Care Society, 5841 Cedar Lake Road, Minneapolis, MN 5541, USA. No: 26029."},
            {"text": "Life member of Research society of Anaesthesiology& clinical pharmacology: C-122-L"},
            {"text": "Kolli S. Chalam, is a Member of Board of Studies, RGUHS"},
            {"text": "Dr Kolli S. Chalam is the scientific committee member of ISNACC conference to be held in Bangalore 2016. Visit isnacc2016.org/organizing-committee.html DR. CHALAM K. 17th Annual Conference of Indian Society of Neuro anaesthesiologyand Critical Care", "year": "2016"},
            {"text": "Kolli S. Chalam serves as member Board of Studies - AHS, RGUHS"},
            {"text": "Kolli S. Chalam, Examiner for fellowship in cardiovascular anaesthesia under Indian college of Anaesthesiologists (ICA) held on 17th June 2018 at Narayana Institute of Cardiac Sciences (NICS), Narayana health city.", "year": "2018"},
            {"text": "Kolli S. Chalam served as External Appraiser for National Board of Examination 16.4.2015 at Kochi, Kerala.", "year": "2015"},
            {"text": "Served as member of scientific committee of Indian Society of Neuro Anesthesiology & Critical Care (ISNACC), an international conference, held at NIMHANS, Bangalore in February 2016", "year": "2016"},
            {"text": "Kolli S. Chalam, NBE accreditation assessor"},
          ],
        },
        { title:"Postgraduate Research & Dissertations", count:72,
          entries:[
            {"text": "Study of the haemodynamic response and brain relaxation with 3% hypertonic saline and 20% mannitol in patients undergoing craniotomy for supratentorial tumours. 2007", "year": "2007"},
            {"text": "To Study the efficacy of intranasal NTG and topical NTG prior to laryngoscopy and intubation in attenuating the cardiovascular response during laryngoscopy and endotracheal intubation in patients undergoing off-pump Coronary Artery Bypass Grafting. 2007", "year": "2007"},
            {"text": "A prospective randomised study of the time taken and stress response during endotracheal intubation in patients with anticipated difficult airway using 3 different techniques 1. Macintosh Laryngoscope 2. Intubating LMA 3.Fiberoptic bronchoscpe in patients undergoing off-pump Coronary Artery Bypass Grafting. 2008", "year": "2008"},
            {"text": "Hemodynamic responses during fiberoptic bronchoscopic intubations: comparison of propofol and thiopentone based anaesthesia techniques: 2009", "year": "2009"},
            {"text": "Study of clinical effect of oral clonidine on peri-operative hemodynamic outcome in neuro surgical patients. Dissertation work for submission of NBE 2009.", "year": "2009"},
            {"text": "Study of effect of IV Magnesium on the hemodynamics and post operative pain relief in lumbar discetomy surgeries. 2009.", "year": "2009"},
            {"text": "Study of effects of Gabapentin pre-medication on post operative pain relief in patients undergoing lumbar discectomy’, 2010.", "year": "2010"},
            {"text": "Comparative study of caudal epidural Ropivacaine versus Bupivacaine on the postoperative pain relief in lumbar discetomy surgeries. 2010.", "year": "2010"},
            {"text": "Study of palonosetron to control postoperative nausea and vomiting in tympanoplasty surgeries. 2010.", "year": "2010"},
            {"text": "A comparative study between intranasal midazolam and intranasal ketamine as a premedication in children undergoing surgical procedures.2010.", "year": "2010"},
            {"text": "Study of intubation response with Dexmedetomidine versus fentanyl based anesthesia for lumbar discetomy surgeries; 2010.", "year": "2010"},
            {"text": "A comparative study of hemonaynamic responses to tracheal intubation using Airtraq versus macintosh laryngoscope in routine airway management of adult patients undergoing ASD surgeries.2011.", "year": "2011"},
            {"text": "A comparative study of ultrasound guided single shot paravertebral block with Bupivacaine versus Ropivacaine for the post operative pain relief in children undergoing thoracotomy for PDS ligation. 2011", "year": "2011"},
            {"text": "A comparative study of intravenous Dexmedetomidine versus propofol based sedation for awake fiberoptic intubation along with airway blocks in cervical discectomy patients. 2011.", "year": "2011"},
            {"text": "A comparative study of endotracheal intubation using ILMA versus fiberoptic laryngoscopy in patients undergoing cervical discectomy under dexmedetomidine based general anaesthesia: 2012.", "year": "2012"},
            {"text": "A comparative study between intranasal dexmedetomidine and intranasal ketamine as a premedication in paediatric cardiac surgeries.2012", "year": "2012"},
            {"text": "A study of the efficacy of Butorphanol as an additive to single shot caudal with Bupivacaine, in adults undergoing Lumbar Spine Surgery Comparison with Bupivacaine alone.2012.", "year": "2012"},
            {"text": "A comparative study of real time ultrasound guided versus land mark technique for central venous line placement in the internal jugular vein in patients undergoing coronary artery bypass graft surgery 2012.", "year": "2012"},
            {"text": "Comparison of physical assessment and ultrasonographic evaluation of the airway to predict Cormack and Lehane grade on laryngoscopy 2013.", "year": "2013"},
            {"text": "Comparative study between dexmedetomidine and fentanyl for sedation in mechanically ventilated post operative OPCAB patients: 2013.", "year": "2013"},
            {"text": "A comparative study of the use of two indirect intubating devices – intubating laryngeal mask airway and video laryngoscope (CMAC) with respect to ease of intubation and post intubation hemodynamic changes: 2013.", "year": "2013"},
            {"text": "A comparative study of ropivacaine with neostigmine and Bupivacaine with neostigmine used for spinal(subarachnoid)aesthesis in patients undergoing lower abdominal and infra-umbilical surgeries.-2015", "year": "2015"},
            {"text": "Comparing the efficacy of caudal analgesia using levobupivacaine with fentanyl or levobupivacaine with dexmedetomidine in paediatric atrial septal defect repair surgeries- a prospective randomised double blinded study"},
            {"text": "A comparative study of Haemodynamic Response to tracheal Intubation Using Airtraq versus Macintosh Laryngoscope in Routine Airway Management of Adults Patients Undergoing ASD Closures Surgeries”"},
            {"text": "A Comparative Study of Intravenous Dexmedetomidine versus Propofol Based Sedation for Awake Fiberoptic Intubation Along with Airway Blocks in Cervical Discectomy patients”"},
            {"text": "A Comparative Study of Ultrasound Guided Single Shot Paravertebral Block with Ropivacaine Versus Bupivacaine for Post-Operative Pain Relief in Children Undergoing Thoracotomy for PDA Ligation”"},
            {"text": "A Comparative Study of Ultrasound Guided Single Shot Paravertebral Block with Ropivacaine Versus Bupivacaine for Post-Operative Pain Relief in Children Undergoing Thoracotomy for PDA Ligation”"},
            {"text": "“A comparative study of Endotracheal Intubation using ILMA versus Fiberoptic Laryngoscopy in patients undergoing cervical discectomy under dexmedetomidine based General Anaesthesia”"},
            {"text": "“A comparative study between Intranasal dexmedetomidine and intranasal Ketamine as a premedication in paediatric Cardiac surgeries”"},
            {"text": "A comparative study between dexmedetomindine and fentanyl I.V infusion for sedation during mechanical ventilation in post operative off pump CABG patients."},
            {"text": "“A comparative study of perioperative analgesia using subarachnoid (spinal) levobupivacaine - butorphanol and levobupivacaine - fentanyl in patients undergoing lower limb surgery”"},
            {"text": "A Prospective Controlled Comparative Clinical Study of Effect of Adding 25 µg fentanyl versus 5 µg dexmedetomidine to spinal(subarachnnoid) Block with 15 µg of 15% Isobaric Levobupivacaine in patients undergoing Elective Gynaecological Surgeries"},
            {"text": "A comparative study of two methods used to attenuate the hemodynamic response after pin fixation in neurosurgical patients undergoing supratentorial craniotmy under going general anaesthesia viz scalp block using levobupivacaine,and iv fentanyl"},
            {"text": "A comparative study of Ropivacaine with Fentanyl and Bupivacaine with Fentanyl used for spinal(subarachnoid) anaesthesia in patients undergoing lower abdominal and infra-umbilical surgeries"},
            {"text": "A comparative study of intranasal clonidine versus intranasal dexmedetomidine as pre-medication in children undergoing PDA ligation surgery"},
            {"text": "Pre-emptive Analgesia for Postoperative Pain Relief Following Surgery for Lumbar Intervertebral disc Prolapse- A Prospective study comparing the efficacy of Ropivacaine with Bupivacaine as a single caudal Epidural Injection Combination with Fentanyl”"},
            {"text": "“A Comparative Study of Intravenous Ondansetron and Palonosetron in the Prevention of Post – Operative Nausea And Vomiting in Patients Undergoing Tympanoplasty and Mastoidectomy Surgeries Under General Anesthesia”"},
            {"text": "“Evaluation of Intra-Operative Haemodynamic Effects of Intravenous Dexmedetomidine Based versus Intravenous Fentanyl Based Balanced Anaesthesia in Patients undergoing Lumbar Disc Surgeries- A Comparative Study”"},
            {"text": "“Study of the Effect of Magnesium Sulphate on Speed of onset and Duration of Vecuronium Bromide induced Neuromuscular Block”"},
            {"text": "“A Randomized Comparative Study of the Haemodynamic Responses to Endotracheal Intubation in Patients with Anticipated Difficult Airway undergoing Coronary Artery Bypass Grafting using Macintosh Laryngoscope, Intubating Laryngeal Mask Airway and Fibre Optic Bronchoscope”."},
            {"text": "Acomparative study of preoperative glycaemic control in patients undergoing coronary artery bypass grafting under thoracic epidural anaesthesia combined with general anaesthesia versus general anaesthesia"},
            {"text": "Study of the Effect of Bilateral Maxillary Nerve Block on Haemodynamic Responses during Trans- Sphenoidal Surgery of pituitary"},
            {"text": "“A randomized comparative study of Bupivacine and Levo Bupivacine for single shot Ultra- sound guided Transverse Abdominis Plane(TAP) block for postoperative pain management in patients undergoing infra-umbilical surgeries”,2016", "year": "2016"},
            {"text": "“A randomized comparative study of the efficacy of ropivacaine and bupivacaine for use in spinal (subarachnoid) anaesthesia in paediatric patients undergoing infra-umbilical surgery”"},
            {"text": "“A Prospective randomized controlled double blinded study of the efficacy of endoscope guided transnasal bilateral sphenopalatine Ganglion Block with Levobupivacaine,as an adjuvant to General anaesthesia, in patients undergoing Endoscopic pituitary surgeries.” . 2015", "year": "2015"},
            {"text": "Comparing the efficacy of caudal analgesia using levobupivacaine with fentanyl or levobupivacaine with dexmedetomidine in paediatric atrial septal defect repair surgeries- A prospective randomised double blinded study,2016", "year": "2016"},
            {"text": "“A Randomised comparative study of the efficacy of Ropivacine with Neostigmine and Bupivacaine with Neostigmine used for spinal (subarachnoid) anaesthesia in patients undergoing infra-umbilical surgeries.” 2015", "year": "2015"},
            {"text": "A study comparing the efficacy of two anaesthetic techniques for lumbar spine surgeries-spinal anaesthesia versus general anaesthesia”"},
            {"text": "“A comparative study of two methods used to attenuate the hemodynamic response and stress responses after pin fixation in neurosurgical patients undergoing craniotomy either with scalp block or pin site infiltration using levobupivacaine”"},
            {"text": "Study of Hemodynamicsresponses to endotracheal Intubation with Trachlight and Conventional Laryngoscopy"},
            {"text": "Study of Haemodynamic responses to endotracheal intubation using intubating laryngeal mask airway( Fastrach tm) and direct laryngoscopy (mcintosh blade)"},
            {"text": "To study and compare the efficacy of intranasal nirtoglycerine and topical nitroglycerine prior to laryngoscopy and intubation in attenuating the cardiovascular response during laryngoscopy and endotracheal intubation in patients undergoing coronary artery bypass graft surgery"},
            {"text": "Study of hemodynamics responses to Endotracheal Intubation with Trachlight and Conventional Laryngoscopy and Fiberoptic intubation"},
            {"text": "“A Prospective Randomized comparative study of the efficacy of magnesium sulphate with Bupivacaine with fentanyl used for spinal (subarachnoid) anaesthesia in patients undergoing lumbar spinal surgeries .”, 2017", "year": "2017"},
            {"text": "“A Prospective Randomized Controlled Double blinded study of the efficacy of dexmedetomidine as an Adjuvant to General Anaesthesia, in patients undergoing Endoscopic Transnasal surgeries.” 2017", "year": "2017"},
            {"text": "“A Comparative study of intravenous combination of dexmedetomindine and Ketamine versus Fentanyl and Ketamine as sedative agents in children undergoing interventional cardiac catherization procedures.” 2017", "year": "2017"},
            {"text": "“To compare the efficacy of post operative analgesia between epidurally administered Buprenorphine or clonidine as adjuvant in combination with Ropivacaine in patients undergoing infra-umbilical surgeries.” , 2017", "year": "2017"},
            {"text": "“A study comparing the efficacy of two anaesthetic techniques for lumbar spine surgeries-spinal anaesthesia versus general anaesthesia”.2017", "year": "2017"},
            {"text": "“A comparative study of intranasal Clonidine versus Intranasal Dexmedetomidine as pre medication in children undergoing PDA ligation surgery”, 2017", "year": "2017"},
            {"text": "“A Comparative study of efficacy of Propofol versus Dexmedetomidine in total Intravenous Anaesthesia Technique for Intraoperative Neurophysiological Monitoring in patients undergoing neurosurgery.”,2018", "year": "2018"},
            {"text": "“A prospective, randomized double blind study to compare and evaluate oral Pregabalin and oral clonidine as premedication in spine surgeries under prone position,2018", "year": "2018"},
            {"text": "A comparative study of Ropivacaine and Levo Bupivacaine with fentanyl as an adjunct for single shot Ultra-sound guided Subcostal Transverse Abdominis Plane block for postoperative pain management in patients undergoing LaproscopicCholecystectomy”"},
            {"text": "“A prospective randomized double blinded parallel study comparing the efficacy of the combination of Isobaric levobupivacaine with variable concentration of preservative free ketamine and Isobaric levobupivacaine alone in patients undergoing elective lower abdominal and lower limb surgeries under spinal Anaesthesia.”, 2019", "year": "2019"},
            {"text": "A Prospective, Randomized Study To Compare And Evaluate Dexmedetomidine Versus Fentanyl As An Adjuvant With Bupivacaine In Bilateral Ultrasound-Guided Erector Spinal Block For Postoperative Analgesia In Adult Atrial Septal Defect Repair Surgery,2019", "year": "2019"},
            {"text": "Comparative study of effect of different durations of preoperative fasting on gastric pH and volume, 2019", "year": "2019"},
            {"text": "Comparative study of the efficacy of caudal analgesia utilizing levobupivacaine with ketamine or levobupivacaine with fentanyl in paediatricpatientsundergoing ASD repair surgeries under cardiopulmonary bypass- a prospective randomised double blind study.2019", "year": "2019"},
            {"text": "Comparative study of Fentanyl versus Butorphanol as an adjuvant toBupivacaine in Spinal Anaesthesia in Lumbar Discectomies, 2019.", "year": "2019"},
            {"text": "A prospective randomized comparative study of emergence time in patients undergoing elective craniotomy for tumour resection under general anaesthesia with isoflurane using low versus medium fresh gas flow during maintenance of anaesthesia"},
            {"text": "A comparative study of the efficacy of bilateral ultrasound guided transverse thoracic plane block utilizing levobupivacaine 0.25% with fentanyl 1mcg/kg in comparision with iv fentanyl 0.5mcg/kg/hr for postoperative analgesia in patients undergoing median sternotomy procedures : a prospective randomised study"},
            {"text": "A comparative evaluation of the hemodynamic response and ease of intubation with king vision video laryngoscope and fiber optic bronchoscope in adult patients undergoing tracheal intubation for general anaesthesia: a prosepectve and randomized study ."},
            {"text": "Multi modal monitoring of depth of anesthesia to evaluate"},
            {"text": "anaesthetic consumption and incidence of post operative delirium in patients undergoing cardiac surgery under cardiopulmonary bypassa prospective randomised comparative study."},
          ],
        },
        { title:"Research Projects", count:1,
          entries:[
            {"text": "Ongoing project in collaboration with GE health care in CTVS critical care entitled “Current (High fidelity) monitoring and innovative predictive algorithms to reduce Length of ICU stay, morbidly, mortality rates in the cardiac surgical intensive care unit”."},
          ],
        },
        { title:"Conferences Organised", count:263,
          entries:[
            {"text": "Critical Care Medicine update 2009 on 29th May 2009. Scientific sessions consisted of didactic lectures and workshops with faculty from USA with an attendance of 150 delegates.", "year": "2009"},
            {"text": "Two day CME entitled ‘Critical care medicines update 2010’ on 29-30th May 2010. It included didactic lectures, ECHO (TEE) workshop, PALS workshops with an audience of 108 delegates.", "year": "2010"},
            {"text": "ISA city branch, Bangalore 2011 meet with an academic session consisted of didactic lectures, video sessions with 72 members.", "year": "2011"},
            {"text": "SANCON 2013– The SSSIHMS Anaesthesia Conference (SANCON) 2013 on Anaesthesia Machine & Monitoring Equipments was held on 29-30 March 2013. The focus of SANCON was towards integrating textbook with equipment use to suit day-to-day OT Anaesthesia practices. Anaesthesia equipment and instrumentation is currently not covered to the extent required in postgraduate medical teaching in India. SANCON provided an opportunity to address this gap, by facilitating delegate interaction with well renowned faculty using didactic sessions & workstations. Click here for report.", "year": "2013"},
          ],
          subgroups:[
            { title:"Faculty Lectures", entries:[
              {"text": "Gas Supply & Distribution System- Dr Radhika Dhanpal, St. Johns Medical College, Bangalore"},
              {"text": "Evolution of Anaesthesia Delivery System- Dr Pankaj Kundra , JIPMER, Pondicherry"},
              {"text": "Anesthesia Machines- Dr Baljit Singh, GB Pant Hospital, New Delhi"},
              {"text": "eCharting Solutions in Critical Care and Anesthesia Data Management Systems-Dr A Thanga Prabhu, GE Healthcare IT-India"},
              {"text": "Anesthesia Ventilators- Dr T R Chandrasekhar, K R Hospital, Bangalore"},
              {"text": "Breathing Systems- Dr S S Harsoor, BMCRI, Bangalore"},
              {"text": "Pediatric Anesthesia Equipments- Dr Kolli S. Chalam, SSSIHMS, Bangalore"},
              {"text": "Vaporizers- Dr Aurita R Kamat, SSSIHMS, Bangalore"},
              {"text": "New Tools on Anesthesia Systems to Simplify Low"},
              {"text": "& Minimal Flow Anesthesia Practice-Ms. Emilia Dmello, GE Healthcare, Bangalore"},
              {"text": "Workshops:"},
              {"text": "Anaesthesia Machine & Workstations"},
              {"text": "Monitoring"},
              {"text": "Ultrasound"},
              {"text": "eCharting & Data Management"},
            ] },
            { title:"Day 2 lectures", entries:[
              {"text": "Airway Monitoring- Dr Pankaj Punetha, SSSIHMS, Bangalore."},
              {"text": "Neuromuscular Monitoring- Dr Sunil Chhajwani, SSSIHMS, Bangalore."},
              {"text": "Cardiovascular Monitoring- Dr K Muralidhar, Narayana Hrudayalaya, Bangalore."},
              {"text": "Neurological Monitoring - BIS & Entropy- Dr G S Umamaheshwar Rao, NIMHANS Bangalore."},
              {"text": "Advanced Monitoring Parameters indicative of Adequacy of Anaesthesia in high risk patients-"},
              {"text": "Dr Sushant Thappa, GE Healthcare, Bangalore"},
              {"text": "Ultrasound for Anaesthesiologists – Basics & Beyond- Dr Sanjaya Vishwamitra, SSSIHMS, Bangalore."},
              {"text": "Ultrasound for Vascular Access & Hemodynamic Monitoring- Dr Manimala Rao, Yashoda Hospital, Hyderabad."},
              {"text": "Ultrasound for Airway, Spine & Nerve Blocks- Dr Murali Chakravarthy, Fortis Hospitals, Bangalore."},
              {"text": "Radiation safety for the Anaesthesiologist.-Dr Baljit Singh, GB Pant Hospital, New Delhi"},
              {"text": "SANCON 2014 CONFERENCEHeld on 29TH & 30TH March 2014. The total number of delegates attended was 196 & Faculty 15 numbers. Feedback from Faculty & Delegates: Well appreciated, Free Registration, Free Food.", "year": "2014"},
              {"text": "The Scientific program consisted the following sessions: Anaesthesia Machines, Preparation of anaesthesia, anaesthesia ventilation, breathing circuits, Intraoperative cardiac arrest, difficult paediatric airway, vaporizes, regional anaesthesia in obese patients, difficult IV access, ECG, ABG cardiac output, Tee as an Intra-operative monitor, flow volume loops & radiology for anaesthesia."},
            ] },
            { title:"FACULTY LECTURES", entries:[
              {"text": "Dr Pankaj Kundra Anesthesia Machines"},
              {"text": "Dr Azam Preparation for Anesthesia"},
              {"text": "Dr T R Chandrashekar Anesthesia Ventilators"},
              {"text": "Dr Geetanjali Tulapurkar Breathing Circuits"},
              {"text": "Dr Radhika Dhanpal Intraoperative Cardiac Arrest"},
              {"text": "Dr Kolli S. Chalam Difficult Pediatric Airway"},
              {"text": "Dr Padmaja Vapourizers"},
              {"text": "Dr Subramanyam Mahankali Regional Anesthesia in Obese Patients"},
              {"text": "Dr Baljit Singh How to manage a difficult case."},
              {"text": "Workshops:"},
              {"text": "TEE Anesthesia Machines"},
              {"text": "CPR Megacode ECG Spotters"},
              {"text": "Sonoanatomy ABG Spotters"},
              {"text": "Difficult Airway X Ray Spotters"},
            ] },
            { title:"Lectures day 2", entries:[
              {"text": "Dr Muralidhar K ECG"},
              {"text": "Dr Sunil Chhajwani Difficult IV Access"},
              {"text": "Dr Vijaya Patil ABG"},
              {"text": "Dr Murali"},
              {"text": "Chakravarthy Cardiac Output"},
              {"text": "Dr Srikanth Sola TEE as an Intraoperative Monitor"},
              {"text": "Dr Pankaj Punetha Ventilator graphics"},
              {"text": "Dr Zarina Abdul Assis Radiology for Anesthetists"},
              {"text": "PG Debate"},
              {"text": "GA vs. Regional for Orthopedics"},
              {"text": "GA vs. regional for Obstetrics"},
              {"text": "Awake vs. Asleep Intubation for difficult intubation"},
              {"text": "CARDIAC ANESTHESIA UPDATE 2014 under the auspices of IACTA 2014CME was held on 13th & 14th December 2014. The total number of delegates was 160 & Faculty 28. It still adorns in IACTA a national official web page http://iacta.co.in/WP_iacta/portfolio/cardiac-anesthesia-update-bangalore/", "year": "2014"},
              {"text": "The scientific program consisted the following sessions: Low cardiac output syndrome, Pulmonary Hypertension – current trends in Mgmt, Cardiac radiology – review of ct & MRI images, Hemodynamic assessment by TEE. Feedback from Faculty & Delegates: Conduct such CME very often."},
              {"text": "Lectures: Low Cardiac Output Syndrome-Dr Poonam Malhotra, AIIMS, New Delhi"},
              {"text": "Pulmonary Hypertension – Current Trends in Mgmt- Dr Naman Shastri, Ahmedabad."},
              {"text": "Cardiac Radiology – Review of CT & MRI Images-Dr Srikanth Sola, SSSIHMS"},
              {"text": "Hemodynamic Assessment by TEE-Dr Muralidhar K, Narayana Hrudayalaya, Bangalore"},
              {"text": "LV Systolic and Diastolic Fx.Assessment by TEE-Dr Murali Chakravarthy, Fortis, Bangalore"},
              {"text": "Assessment of RV-Dr Naman shastri, Ahmedabad"},
              {"text": "Management of Bleeding Cardiac Surgical Patient-Dr.Parimala Simha, Jayadeva, Bangalore"},
              {"text": "Renal Dysfunction post Cardiac Surgery-Dr Poonam Malhotra, AIIMS, New Delhi"},
              {"text": "Management of Failing Fontan-Dr. Rajnish Garg, Narayana Hrudayalaya"},
              {"text": "Cardiac Arrest in ICU-Dr Sathya Swaroop Patnaik, SSSIHMS"},
              {"text": "MACS – Role of Anesthesiologist-Dr Dharmesh Agarwal, Apollo, Bangalore"},
              {"text": "Heart Transplant – Anesthetic Implications-Dr Kolli S. Chalam, SSSIHMS, Bangalore"},
              {"text": "Ventricular Assist Devices-Dr Jeevanandam, Prof Univ. Chicago Medicine;Video confering"},
              {"text": "Anesthesia considerations for Robotic CardiacSurgery : Video- University of ChicagoMedicine"},
              {"text": "Organ Protection on CPB-Dr Rajan Anand, SSSIHMS, Puttaparthi"},
              {"text": "Perfusion Emergenies – Detection and Management-Dr A M Jagadeesh, Jayadeva, Bangalore"},
              {"text": "TEE Assessment of Valve Repairs-Dr Raghu, Narayana Hrudayalaya, Bangalore"},
              {"text": "Epicardial Echocardiography-Dr T A Patil, Fortis, Bangalore"},
              {"text": "SANCON 2015 CONFERENCEHeld on 14TH& 15TH March 2015. The total number of delegates attended was 200 & Faculty 12 numbers. Well appreciated, Free Registration, Free Food", "year": "2015"},
              {"text": "The Scientific program consisted the following sessions: Anaesthesia Machines, anaesthesia ventilation, breathing circuits, difficult paediatric airway, vaporizes, regional anaesthesiaequipment, difficult airway equipment, Man Vs Machine, Feedback from Faculty & Delegates."},
              {"text": "Lectures"},
              {"text": "Dr C.L.Gurudutt,Mysuru - Anaesthesia Machine"},
              {"text": "Dr Pankaj Kundra, JIPMER Vaporizers"},
              {"text": "Dr Radhika Dhanpal, SJMC,Benguluru-Breathing Circuits"},
              {"text": "Dr Baljit Singh, GP Pant Hospital, Delhi- OT Environment-Gases, Temperature & Safety"},
              {"text": "Dr Ramkumar, KMC, Manipal Ventilation in the OT & Flow-Press-Volume loops"},
              {"text": "Dr K M Deepak, Fortis, Bengaluru Ultrasound & the Anaesthetist"},
              {"text": "Panel Discussion: “Man Vs Machine – Are we over dependent on the Monitor” Dr RamkumarModerator: Dr Baljit SinghDr Kodandaram Dr Mary Korula Dr Sriganesh"},
              {"text": "PGs to participate in Best Poster Competition"},
              {"text": "Dr Subramaniyam M,ColumbiaAsia Hospital Benguluru-Regional Anaestheisa equipment"},
              {"text": "Dr T R Chandrasekhar,KR Hospital, Bengaluru-Arterial Blood Gas Analysis"},
              {"text": "Dr Kolli S. Chalam, SSSIHMS, Bengaluru - Difficult airway equipment"},
              {"text": "Dr Rebeca Jacob,Columbia Asia Hospital, Bengaluru Paediatric Airway Equipment"},
              {"text": "Dr Balabhaskar, VIMS, Bellari -Standard Monitoring"},
              {"text": "Dr Muralidhar K, NH Narayana Hospital, Bengaluru-CardiovascularMonitoring"},
              {"text": "Dr Badrinarayan, NIMHANS, Bengaluru Central Nervous System Monitoring"},
              {"text": "Workshop 1: Machine / Workstation, Breathing Circuits, Masks, Cylinders, Ventilators."},
              {"text": "Workshop 2: Monitors - Cardiac, ECG, SPO2, BP(NBP) &"},
              {"text": "(IBP0; Cardiac Output CPR - Megacode : Hands on)"},
              {"text": "Workshop 3: Monitors - CNS, EEG, BLS NHT, TCP, SSEP SUNO"},
              {"text": "Anatomy for Vascular Access / Echo Hands on"},
              {"text": "Workshop 4: Airway Equipment (Difficult airway –FOB,VLS:Hands on)Regional Anaesthesia of ABG / XRays"},
              {"text": "Sri Sathya Sai IACTACardiac Anaesthesia Update 2016", "year": "2016"},
              {"text": "Dept of anaesthesiology & CCM conducted Sri Sathya Sai IACTA Cardiac Anaesthesia Update 2016, under the auspices of IACTA, Bangalore on 12th and 13th November 2016. The two day CME had 12 didactic presentations and one live TEE demo held by leading professionals in Cardiac Anesthesia in Bangalore and across India. 39 faculty and 98 practicing anesthesiologists, fellows and medical students attended the event.", "year": "2016"},
              {"text": "Lectures:"},
              {"text": "Cardiac Surgery in A Pregnant Patient"},
              {"text": "o Regional Anaesthesia in Cardiac Surgery"},
              {"text": "o Diastolic Dysfunction"},
              {"text": "o Neonatal/ Pediatric CPB"},
              {"text": "o TGA"},
              {"text": "o Single Ventricle Physiology"},
              {"text": "o CTEPH"},
              {"text": "o Aortic Aneurysms"},
              {"text": "o Redo Cardiac Surgery"},
              {"text": "o Minimal Access Cardiac Surgery"},
              {"text": "o Haemodynamic Assessment By TEE"},
            ] },
            { title:"DIDACTIC LECTURES", entries:[
              {"text": "Dr. Muralidhar Kanchi, Narayana Hrudayalaya, Blr"},
              {"text": "Dr. Murali Chakravarthy, Fortis Hospitals, Blr"},
              {"text": "Dr. A M Jagadeesh, SJICS, Blr"},
              {"text": "Dr. Naman Shastri, SAL Hospital, Ahmedabad"},
              {"text": "Dr. Shrinivas G, SCTIMST, Kochi"},
              {"text": "Dr. Ranjith Karthekeyan, SRMC, Chennai"},
              {"text": "Dr. Parimala Simha, SJICS, Blr"},
              {"text": "Dr. Keshav Murthy,Narayana Hrudayalaya, Blr"},
              {"text": "Dr. Jayaprakash, Fortis Hospitals, Blr"},
              {"text": "Dr. Prabhakar V, SJICS, Blr"},
              {"text": "INHOUSE FACULTY :• Dr Kolli S. Chalam, Dr. Rajan Anand, • Dr. Anitha Diwakar, • Dr. Anuradha Kamath, • Dr. Sathya Swaroop Patnaik"},
              {"text": "Workshops: 1. ABP & ECMO 2. o Cardiac Cath Analysis 3. o TEE Simulation"},
              {"text": "FIACTA Practical Viva Stations"},
              {"text": "Case Discussions: 1.Valvular Heart Disease 2. Coronary Artery Disease"},
              {"text": "3.Cyanotic Congenital Heart Disease"},
              {"text": "8 Indo US Critical Care Medicine Update 2016 : Department of Anesthesiology and Critical Care Medicine, SSSIHMS white field, Bangalore conducted Indo-US Critical Care Update2016 in collaboration with Baylor College of Medicine Texas; University of Texas, USA and also Indian society of critical care medicine on 16th & 17th January 2016. Total delegates attended both days were 225 (146 doctors and 65 nurses) from various medical colleges, corporate hospitals from Karnataka, Andhra, Kerala and Maharashtra. Some are of senior consultant and professor level category. Among the faculty were Prof (Dr).Kalpalatha Guntupalli, a leading Pulmonologist who is a President of 20,000 US chest physicians; Dr Shankar Gopinath chief Neuro surgeon and also Dr Joseph Kass, Neurologist and Assistant Dean of Baylor College of Medicine, Texas", "year": "2016"},
              {"text": "Published on 15th Jan 2016’ Times of India, Bangalore edition.", "year": "2016"},
              {"text": "http://www.thehansindia.com/posts/index/Health/2016-01-18/Photos-Indo-US-Critical-Care-Medicine-Conference-at-SSSIHMS-/200893", "year": "2016"},
              {"text": "http://www.srisathyasai.org.in/Pages/Announcements/CTPressRelease18Jan2016.htm"},
            ] },
            { title:"Indo US Critical Care Medicine Update 2017", entries:[
              {"text": "Department of Anesthesiology and Critical Care Medicine, SSSIHMS white field, Bangalore Conducted Indo-US Critical Care Update2016 in collaboration with Baylor College of Medicine Texas; University of Texas, USA and also Indian society of critical care medicine on 7th& 8th January 2017 Total delegates attended both days were 140 from 9 states of India from various medical colleges, corporate hospitals from Karnataka, Andhra, Kerala and Maharashtra. Some are of senior consultant and professor level category. Among the faculty were Prof (Dr).Kalpalatha Guntupalli, a leading Pulmonologist who is a President of 20,000 US chest physicians; and Dr Mohan Kilaru, Trauma surgeon from St George Medical School, New York were part of the conference The day ended with an address to the delegates by Sri K Chakravarthi, Trustee, Sri Sathya Sai Central Trust on Swami and the uniqueness of His mission.", "year": "2017"},
              {"text": "On the second day, 2 workshops were arranged for the delegates. The workshop on Ultrasound in ICU had workstations on Lung and airway ultrasound, transcranial Doppler, transthoracic echocardiography, vascular ultrasound and FAST Scan. Another workshop on Mechanical Ventilation had stations on basic and advanced modes of ventilation including non invasive ventilation, NAVA and Smartcare. Over 140 delegates from 9 states of India participated in the conference. Apart from the international faculty, reputed national faculty included Dr Jose Chacko, Director- ICU, NH, Dr TR Chandrashekar, Director, KR Hospital, Dr Predeep Rangappa, Secretary, ISCCM, Bengaluru, Dr Rajesh Shetty, Chief of Intensive Care, Manipal Hospital and Dr Kolli S. Chalam, Head of Department, Anaesthesiology, SSSIHMS, Whitefield."},
              {"text": "Along with the conference, a Critical Care Nursing program was also organized on 7th January 2017 to update the knowledge and skills of nursing staff. The program was attended by 74 nurses. The international faculty and volunteers also conducted a health screening camp for staff and relatives of SSSIHMS and examined over 100 patients on 8th January 2017. Dr Shridevi Devaraj, Medical Director and Professor of Pathology and Immunology, Baylor College of Medicine reviewed the blood investigations of all the patients.", "year": "2017"},
            ] },
            { title:"Sri Sathya Sai IACTACardiac Anaesthesia Update 2017", entries:[
              {"text": "Under the auspices of IACTA_BLR was held on 14th& 15th October 2017 .The focus of CARDIAC ANESTHESIA UPDATE was towards integrating theoretical knowledge with the practical skills to suit our day-to-day work in operating rooms and ICUs. Recent advances with the review of world literature deliberated were by renowned faculty using didactic lectures, case discussions, workshops and FIACTA examinations.", "year": "2017"},
              {"text": "The two day CME had 12 didactic presentations and one live TEE demo held by leading professionals in Cardiac Anaesthesia in Bangalore and across India. 30 faculty and 83 practicing Anaesthesiologists/fellows/DM/FNB c Anaesthesiology students across India were exposed to the latest cardiac Anaesthesia update. There were 83 delegates and 30 faculty on, the 14th& 15th Oct 2017 days for all lectures, case discussions and workshops", "year": "2017"},
              {"text": "LECTURES:"},
              {"text": "Recent advances in neuro-monitoring in cardiac surgery Dr Parimala SP"},
              {"text": "Recent advances in coagulation monitoring Dr Sathya Swaroop.P"},
              {"text": "FIACTA exam Case presentation CABG( by cardiac anesthesia fellow)"},
              {"text": "Moderators: Dr PMChandrasekhar/DrMuralidhar.K/ DrChittaranjan"},
              {"text": "Current trends in management of heart failure and assist devices-Dr Murali Chakravarthy"},
              {"text": "Anesthetic implications for Heart transplant -Dr Suresh Rao K G"},
              {"text": "Aortic dissection: Anaesthesia considerations -Dr Muralidhar.K"},
              {"text": "Current trends in management of heart failure and assist devices-Dr Murali Chakravarthy"},
              {"text": "Anesthetic implications for Heart transplant - Dr Suresh Rao K G"},
              {"text": "Case presentation – Mitral valve Moderators: Dr Dash PK/Dr Suresh Rao KG/Dr KS"},
              {"text": "Kolli S. Chalam"},
              {"text": "Anaesthesia for OPCAB - Dr.Ranjith.K"},
              {"text": "AVR and AV repairs Dr Patil T A"},
              {"text": "Workshops:"},
              {"text": "CPB AND ECMO 2. Cardiac imaging 3. Cardiac catherisation, Dr. Anuraqdha"},
              {"text": "FIACTAA viva stations"},
            ] },
            { title:"Day 2: academics", entries:[
              {"text": "Case presentation – TOF (Jayadeva)DR/ Naman S/Dr Krishna Manohar"},
              {"text": "Anesthetic Considerations in TAPVC -Dr JayaPrakash, Fortis hospital, Bannerghatta"},
              {"text": "Crashed patient in CATH LAB Dr.Anuradha. K"},
              {"text": "ICU Care of post operative pediatric cardiac surgical patients-Dr.Anitha. D"},
              {"text": "Aortic root enlargement and Bentall surgeries: Anaesthesia management-Dr Nagaraja P.S ,"},
              {"text": "TAVI: Anaesthesia concerns Dr Naman Shastri"},
              {"text": "MI Patient for laparotomy for acute intestinal obstruction:Anaesthesia concerns-Dr Kolli S. Chalam"},
              {"text": "Lung Isolation, One-lung Ventilation And Hypoxemia During Lung Isolation-Dr Dharmesh Agrawal"},
              {"text": "The sessions were chaired by eminent Cardiologists, Cardiac surgeons and Cardiac Anaesthesiologists. They include Dr P M Chandrashekara former professor of Jayadeva Institute of Cardiovascular Sciences, Bangalore, Dr P.K. Dash, HOD Cardiology, SSSIHMS, Bangalore, and Dr Patil Jayadeva institute of cardiology & research, Bangalore., Dr.Naman Shastri, Dr.JayaPrakash, Dr.Ranjith Karthikeyan, Dr.Pankaj Punetha were faculty conducted the Conference."},
            ] },
            { title:"Indo US Critical Care Medicine Update 2018", entries:[
              {"text": "Department of Anesthesiology and Critical Care Medicine, SSSIHMS white field, Bangalore Conducted"},
              {"text": "Indo-US Critical Care Update2016 in collaboration with Baylor College of Medicine Texas; University of"},
              {"text": "Texas, USA and also Indian society of critical care medicine on 6th& 7th January 2018 Total delegates attended both days were 192 from 9 states of India from various medical colleges, corporate hospitals from Karnataka, Andhra, Kerala and Maharashtra. Some are of senior consultant and professor level category. Among the faculty were Prof (Dr).Kalpalatha Guntupalli, a leading Pulmonologist who is a President of 20,000 US chest physicians; and Dr Mohan Kilaru, Trauma surgeon from St George Medical School, New York were part of the conference", "year": "2018"},
              {"text": "On the second day, 2 workshops were arranged for the delegates. The workshop on Ultrasound in ICU had workstations on Lung and airway ultrasound, transcranial Doppler, transthoracic echocardiography, vascular ultrasound and FAST Scan. Another workshop on Mechanical Ventilation had stations on basic and advanced modes of ventilation including non invasive ventilation, NAVA and Smartcare. Over 192 delegates from 9 states of India participated in the conference. Apart from the international faculty, reputed national faculty included Dr Jose Chacko, Director- ICU, NH, Dr TR Chandrashekar, Director, KR Hospital, Dr Predeep Rangappa, Secretary, ISCCM, Bengaluru, Dr Rajesh Shetty, Chief of Intensive Care, Manipal Hospital and Dr Kolli S. Chalam, Head of Department, Anaesthesiology, SSSIHMS, Whitefield."},
              {"text": "Along with the conference, a Critical Care Nursing program was also organized on _6th Jan 2018 January 2018 to update the knowledge and skills of nursing staff. The program was attended by 74 nurses. The international faculty and volunteers also conducted a health screening camp for staff and relatives of SSSIHMS and examined over 100 patients on 8th January 2017. Dr Shridevi Devaraj, Medical Director and Professor of Pathology and Immunology, Baylor College of Medicine reviewed the blood investigations of all the patients.", "year": "2017"},
            ] },
            { title:"Sri Sathya Sai IACTACardiac Anaesthesia Update 2018", entries:[
              {"text": "Under the auspices of IACTA_BLR was held on 27th& 28th October 2018 .The focus of CARDIAC ANESTHESIA UPDATE was towards integrating theoretical knowledge with the practical skills to suit our day-to-day work in operating rooms and ICUs. Recent advances with the review of world literature deliberated were by renowned faculty using didactic lectures, case discussions, workshops and FIACTA examinations.", "year": "2018"},
              {"text": "The two day CME had 12 didactic presentations and one live TEE demo held by leading professionals in Cardiac Anaesthesia in Bangalore and across India. 30 faculty and 70 practicing Anaesthesiologists/fellows/DM/FNB c Anaesthesiology students across India were exposed to the latest cardiac Anaesthesia update. There were 70 delegates and 30 faculty on, the 27th& 28th Oct 2018 days for all lectures, case discussions and workshops:", "year": "2018"},
              {"text": "Cardiac cycle and PV Loops-Dr. D K Tempe, GB Pant Hosp,Delhi"},
              {"text": "Diastolic dysfunction-Dr T.A. Patil, Fortis Hospitals,Bangalore"},
              {"text": "Analgesia in cardiac surgery beyond opioids-Dr Murali Chakravarthy, Fortis,Bangalore"},
              {"text": "AORTIC STENOSIS: case discussion: Dr. D K Tempe,Dr. P.M.Chandrashekara"},
              {"text": "Low cardiac output syndrome in children-Dr.Naman Shastri,SAL Hospital,Ahmedabad"},
              {"text": "Chronic Thrombo Embolic Pulmonary Hypertension-DrMuralidhar.K,NH, Bangalore"},
              {"text": "Current Trends In Paediatric Cardiac Anaesthesia-Dr.Claire Barker ,The Freeman"},
              {"text": "Hospital New Castle,UK."},
              {"text": "Case discussion 2: TOF Dr Naman Shastri/Dr Claire Barker"},
              {"text": "Anesthesia management for PA banding-Dr. Keshava Murthy, NH,Bangalore"},
              {"text": "TGA – Anaesthesia considerations Dr Anuradha.K, SSSIHMS"},
              {"text": "WORKSHOP I: Hemodynamic workshop:Dr Naman S,Dr Anuradha.K"},
              {"text": "WORKSHOP II: FIACTA VIVASTATION :Dr. Tempe , Dr.Parimala, Dr.Nagaraja P"},
              {"text": "Case discussion 3 - CAD:Dr. Chittaranjan , Dr Parimala,Dr.Indira Rajani"},
              {"text": "VATS: Anaesthesia considerations Dr Kolli S. Chalam , SSSIHMS"},
              {"text": "Role of anesthetist in Cardiomyopathy-Dr.Jaya Prakash , Fortis hospital,Bangalore"},
              {"text": "CO monitoring - current and advanced:Dr Nagaraja PS , Jayadeva Hosp,Bangalore"},
              {"text": "Coagulopathy in cardiac surgery patients: POC solutions-Dr. Anitha.D, SSSIHMS"},
              {"text": "IHD patient for non-cardiac surgery-Dr Satya Swaroop.P, Hitec Medical College , Bhubaneswar"},
              {"text": "Pregnant patient coming for emergency MVR-Dr.Parimala PS, Jayadeva Hosp,"},
              {"text": "Bangalore"},
              {"text": "FREE PAPER SESSION – Judges: Dr. Parimala PS Dr. Indira Rajani"},
              {"text": "The sessions were chaired by eminent Cardiologists, Cardiac surgeons and Cardiac Anaesthesiologists. They include Dr. Deepak K. Tempe, GB pant hospital, and chancellor of Indian College of Cardiac Anaesthesia (ICCA), Dr P M Chandrashekara former professor of Jayadeva Institute of Cardiovascular Sciences, Bangalore, Dr P.K. Dash, HOD Cardiology, SSSIHMS, Bangalore, and Dr Patil Jayadeva institute of cardiology & research, Bangalore, Dr.Naman Shastri, Dr.JayaPrakash, Dr.Ranjith Karthikeyan, Dr.Pankaj Punetha were faculty conducted the Conference."},
            ] },
            { title:"4TH Indo US Critical Care Medicine Update 2019", entries:[
              {"text": "Department of Anesthesiology and Critical Care Medicine, SSSIHMS white field, Bangalore conducted 4thIndo-US Critical Care Update 2019 in collaboration with Baylor College of Medicine Texas; University of Texas, USA and also Indian society of critical care medicine on 5th& 6th January 2019, for inauguration Chancellor of SSSIHL, Shri.K.Chakravarthi, Director Dr.Sundaresh D C graced the occasion alongwith team from Indo US.", "year": "2019"},
              {"text": "Dr.Kalpalatha , Dr.Marie Baldisseri Dr.Jayaram Guntupalli, Dr.Sai Kaumdi Saridey, Dr.Uma Munur, , Dr.Mayur Narayan, Dr.Ramya Goipinath, Dr.Shamim Badruddin Mawji, Dr.Shanker Gopinath, Dr.Sridevi Devaraj, Dr.Srikanth Damaraju, Dr.Srinivas Murali,"},
              {"text": "Total delegates attended both days were 120 from 9 states of India from various medical colleges, corporate hospitals from Karnataka, Andhra, Kerala and Maharashtra. Some are of senior consultant and professor level category. Among the faculty were Prof Marie Baldisseri, university of Philadelphia Prof (Dr).Kalpalatha Guntupalli, a leading Pulmonologist and recipient of Pravasi Bharatiya Samman award, former President of American college of chest physicians; and Dr Mohan Kilaru, Trauma surgeon from St George Medical School, New York were part of the conference."},
              {"text": "Dr.AS.Hegde, Dr.P.K.Dash, Dr.Kodandaram, Dr.Jose Chacko, Dr.Sheetal Chaurasia, Dr. Srikantiah Hiremath, Dr. T.R. Chandrashekar were Chairpersons for different sessions held"},
              {"text": "Director- ICU, NH, Dr TR Chandrashekar, Director, KR Hospital, Dr Pradeep Rangappa, Secretary, ISCCM, Bengaluru, Dr Rajesh Shetty, Chief of Intensive Care, Manipal Hospital and Dr Kolli S. Chalam, Head of Department, Anaesthesiology, SSSIHMS, Whitefield."},
              {"text": "Along with the conference, a CRITICAL CARE NURSING PROGRAM was also organized on 5th Jan 2019 to update the knowledge and skills of nursing staff. The program was attended by 50 nurses.", "year": "2019"},
              {"text": "FCCS in Obstetrics was also conducted. Thirty candidates appeared and passed the course. American society of critical care medicine issued certificates."},
              {"text": "NBE sponsored two day CME WORKSHOP ON CLINICAL RESEARCH METHODOLOGIES: Thesis Research & Protocol Writing for DNB Trainees was conducted at our institute on 16-02-2019 & 17-02-2019. Thirty DNB candidates registered with NBE attended the two day CME with workshop.", "year": "2019"},
            ] },
            { title:"Academic sessions", entries:[
              {"text": "Introduction"},
              {"text": "Introduction to Research- Dr Kolli S. Chalam,"},
              {"text": "Basic Biostatistics - Dr. R. Srivatsan, PhD"},
              {"text": "Research Faculty, IBAB, Biotech Park, Electronic City"},
              {"text": "Phase I, Bengaluru"},
              {"text": "Application of statistical analysis on clinical data - Prof."},
              {"text": "Srivatsan, Ph.D"},
              {"text": "Writing a research proposal - Dr Kolli S. Chalam, MD"},
              {"text": "HOD, Anaesthesiology, SSSIHMS, whitefield."},
              {"text": "5.Fundamentals of frequently used statistical tests- Dr."},
              {"text": "Padmashree GK, Ph.D, Adjunct faculty, Dept. of"},
              {"text": "Radiology, SSSIHMS, WFD, Bengaluru"},
              {"text": "Presentation, analysis and interpretation of data- Dr."},
              {"text": "Padmashree GK, Ph.D, Adjunct faculty, Dept. of"},
              {"text": "Radiology, SSSIHMS, WFD, Bengaluru."},
              {"text": "Publication of clinical research- Dr Kolli S. Chalam, MD,"},
              {"text": "HOD, Anaesthesiology, SSSIHMS, whitefield"},
            ] },
            { title:"Day 2: lectures", entries:[
              {"text": "Research Methodology - Dr.N.S. Murthy, Ph.D, FAMS, FSMS,"},
              {"text": "Research Director, DRP and Professor and Research"},
              {"text": "Coordinator,(Ex. Emeritus Medical Scientist, ICMR, New Delhi ,"},
              {"text": "Deputy Director ( Sr. Grade), ICPO (ICMR), NOIDA , & Adjunct"},
              {"text": "Prof. University of Tampere, Finland), M.S. Ramaiah Medical"},
              {"text": "College & Hospitals (MSRMC), Bengaluru"},
              {"text": "Ethical consideration and Legal issues in research"},
              {"text": "- Dr. Sanjaya Viswamitra, HOD Radiology, SSSIHMS"},
              {"text": "Quality Control Data management- Dr.N.S. Murthy, Ph.D, FAMS, FSMS"},
              {"text": "Referencing (Vancouver Style) & Basics of Zotero-"},
              {"text": "Dr Kolli S. Chalam"},
              {"text": "Good clinical practice DGCI guidelines; trial registration- Dr."},
              {"text": "Hiremath, HOD CTVS, SSSIHMS"},
              {"text": "Reviewing Literature, Aims and objectives, Results, discussion"},
              {"text": "– Dr Kolli S. Chalam"},
              {"text": "Hands on Exercise- all"},
              {"text": "Hemodynamic Workshop: Was held as pre conference on 25th November 2019. Sixty delegates participated. The Faculty participated were Dr Kolli S. Chalam, Dr.PankajPunetha, Dr.VrushaliChowdary, Dr.Geetanjali T, Dr.Anuradha Kamath, Dr.SameerSethi, Dr.Alex Joseph, Dr.Rajavardhan R, Dr.AnithaDiwakar , Dr.Mnjunath T.", "year": "2019"},
              {"text": "Overview"},
            ] },
            { title:"Cardiovascular physiology & Heart lung interactions – Dr.Geetanjali T", entries:[
            ] },
            { title:"Physics and principles of Arterial pressure monitoring- Dr. Vrushali C", entries:[
            ] },
            { title:"• Physics and principles of CVP monitoring- Dr Kolli S. Chalam", entries:[
            ] },
            { title:"• PA ( Swan Ganz) catheter monitoring- Dr. P.S.N. Raju", entries:[
              {"text": "• Non invasive & Invasive Cardiac output monitoring -Dr. P.S.N. Raju : 20mins"},
              {"text": "• Monitoring microcirculation- Dr.Alex Joseph:20mins"},
              {"text": "• Assessment of fluid responsiveness: static versus dynamic indicators: Dr.Rajavardhan R"},
              {"text": "• & Dr. Manjunath : Use of Perfusion markers: lactate, SvO2, ScvO2, PCO2v-a difference: Dr.Alex Joseph:"},
              {"text": "• How to choose a Vasopressor /Inotrope-Dr.Anuradha Kamath,"},
              {"text": "• Resuscitation and De-resuscitation- Dr.Pankaj Punetha"},
              {"text": "• How to choose best hemodynamic monitoring tool- Dr.Anitha Diwakar,"},
              {"text": "• “Errors and Pitfalls “ in monitoring tools."},
            ] },
            { title:"CLINICAL STATIONS", entries:[
              {"text": "1. ABP monitoring2. CVP monitoring3. PAC monitoring4. CO monitoring- Flotrac5. Echo (TTE/TEE) &USG basic views SIMULATION SESSIONS"},
              {"text": "1. Cardiogenic shock, 2. Septic shock, 3. Hypovolemic orhemorrhagic shock"},
              {"text": "Invited Faculty"},
              {"text": "1. Dr.Alex Joseph,Singapur, 2. Dr. P.S.N. Raju Chennai, 3. Dr.Rajavardhan R& Dr. Manjunath T, Bengaluru"},
            ] },
            { title:"In house FACULTY", entries:[
              {"text": "1. Dr Kolli S. Chalam, -Coordinator, 2. Dr.Pankaj, Punetha,3. GeetanjaliTulapurkar,4. Dr.AnithaDiwakar, 5. Dr.Anuradha Kamath,6. Dr. VrushaliChoudhary."},
            ] },
            { title:"5th Annual Critical Care Medicine Update 2020", entries:[
              {"text": "Department of Anesthesiology and Critical Care Medicine, SSSIHMS White field, Bangalore conducted 5th Annual Critical Care Medicine Update 2020 on 5th January 2020. Department of Anesthesiology and Critical Care Medicine, SSSIHMS white field, Bangalore", "year": "2020"},
              {"text": "conducted 5 th Annual Critical Care Medicine Update 2020 on 5 th January 2020.", "year": "2020"},
              {"text": "Faculty from US Dr.Kalpalatha , Dr.Jayaram Guntupalli, Dr.Namita Sood, Dr.Deepa B"},
              {"text": "Gotus,Dr.Shankar Gopinath Dr.Dharani Narendra,Dr.Akella Chandrasekhar, Dr.Sridevi Devaraj, Dr.Ganesh Yadlapalli, Dr.Shivani Aggarwal, Dr.Ramya Gopinath,"},
              {"text": "Total delegates attended both days were 70 Doctors from different states of India from various medical colleges, corporate hospitals from Karnataka, Andhra, Kerala and Maharashtra. Some are of senior consultant and professor level category."},
              {"text": "The Chairpersons for different sessions held were Dr Kolli S. Chalam, Dr.Hiramath, Head of the Department , CTVS, Dr.Geetanjali , Dr.Prakash ."},
              {"text": "A brief Report on nursing conference (2020)", "year": "2020"},
              {"text": "An update on the5th Annual critical care nursing Conference (2020) held at SSSIHMS Wfd Bangalore on 5/1/2020 between 830am -130pm.", "year": "2020"},
              {"text": "With BHAGWAN’S blessings, at SSSIHMS, our goal is to deliver highest quality care to the patients with utmost love and compassion. This requires highest level of nursing knowledge to provide quality and safe care to the patients. Hence it is, the nurses’ responsibility that, they are equipped with knowledge and skills to practice and provide quality patient care delivery. To optimize the care, we believe that nurses should be given the opportunity to reach the highest skill level by continuing the CNE."},
              {"text": "To achieve this, a regular in‐service training Program was taken up, to improve the Quality Care in the Nursing Services."},
              {"text": "With an inspiration, support and constant guidance from the Director Dr. ShekharRao, Dr Kolli S. Chalam, HOD, and Anesthesia and in charge of Casualty Dept. and his team organized a 5th Annual critical care Nursing update on Sunday 5th January 2020 in charaka Hall at SSSIHMS Wfd, Bangalore. A total of 40 Nursing staff and 10 MLT students participated in the conference.", "year": "2020"},
            ] },
            { title:"CONTINOUS MEDICAL EDUCATION (CMEs)", entries:[
              {"text": "Regularly BLS & ACLS affiliated to M/s Phoenix Institute of Defibrillation & Research Education, Dr.Ashok Garg, Direcotr, Authorised Instructor Dr Kolli S. Chalam, Dr.PankajPunetha,and Senior Manager Mr.ShravanKumar. Till March 2019, total of 621 members are trained and received AHA cards.", "year": "2019"},
            ] },
          ],
        },
        { title:"Poster Presentations, Awards & Medals", count:24,
          entries:[
            {"text": "Anaesthetic Management of Surgery for Posterior Cranial Fossa Tumours in Paediatric Patients: Institutional Experience: Preethi B Reddy, Kolli S. Chalam, Pankaj Punetha."},
            {"text": "Anaesthetic Management of a case of Thymoma presenting with features of Myasthenia Gravis. Preethi B Reddy, Pankaj Punetha, Sunil Chhajwani, Kolli S. Chalam."},
            {"text": "Dr.Shazia Salam, had won “BEST POSTER AWARD”, for paper presented entitled “Anaesthetic management of video assisted thoracic surgery for pulmonary hydatid cyst in a 10 year old male child with seizure disorder” in the 6thAnnual conference of Indian college of Anaesthesiologists’ held in collaboration with University of Minnesota, USA , in association with Society of Ambulatory Anaesthesia (SAMBA) & Malignant Hyperthermia association of the United States (MHAUS) , at Narayana Hrudayalaya Hospital, Bangalore from 21st to 23rd November 2014", "year": "2014"},
            {"text": "Dr.Srirangajoshi presented paper eposter in “Interesting Images” section at Narayana Hrudayala dated 21stAugust 2015.Topic was atrioventricular cushion defect with supramitral ring", "year": "2015"},
            {"text": "Dr.Anitha Diwakar:Presented a paper titled: Comparison of haemodynamic responses to laryngoscopy and intubation with Truview PCDTM, McGrath® and Macintosh laryngoscope in patients undergoing CABG: A Randomized prospective study. During 63rd Annual National Conference of Indian Society of Anesthesiologists ISACON 2015 at Jaipur, 26th to 29th December 2015", "year": "2015"},
            {"text": "Dr.Sathya Swaroop Patnaik attended IACTACON Cardiac anesthesia national conference dated 12th& 14th Feb 2016. He presented 4 papers-", "year": "2016"},
            {"text": "Cardiac surgery postoperative arrest and resuscitation- a single institution 3 year retrospective study of protocol and outcome"},
            {"text": "Difficulty in weaning off CPB in a case of Williams syndrome with Supravalvular aortic stenosis"},
            {"text": "Patient of SV ASD with PAPVC and LSVC for Minimal Access Cardiac Surgery"},
            {"text": "Minimally invasive approach for redo valve surgery- a case series"},
            {"text": "Dr.Isha Samadhiya presented 2 papers at IACTA CON dated 12th& 14th Feb 2016 –", "year": "2016"},
            {"text": "1) Institutional review of MACS ASD cases"},
            {"text": "2) Comparison of tranexamic acid & epsilon amino caproic acid in adult valvular heart surgery"},
            {"text": "Dr Arya James: CPR in parturient and new born simultaneously at obstetric anesthesiologist’s conference at Bangalore"},
            {"text": "Anuradha Kamath, AWARDS: Secured Second Prize in FTEE (Fellowship in Perioperative Transesophageal Echocardiography) conducted by Indian Association of Cardiovascular Thoracic Anesthesiologists (IACTA) in Aug 2019.", "year": "2019"},
            {"text": "Dr.Anuradha Kamath A Prospective Comparative Study Of Procedural Sedation Using High Flow Humidified Nasal Oxygen Versus Hudson Oxygen Mask For Icd And Crtd Insertion In Cardiac Catheterisation Lab…IACTACON 2020 Goa : Won 1st Prize For Original Research", "year": "2020"},
            {"text": "Departmental CLINICAL MEETING & CPR training to peripheral locations"},
            {"text": "CODE BLUE preparations at SSSIHMS Wfd & team - Dr Kolli S. Chalam"},
            {"text": "AHA BLS/ACLS 2015 update, ACLS outing it all together - Dr Pankaj Punetha", "year": "2015"},
            {"text": "Mock code - Dr Sathya S Patnaik"},
            {"text": "Anesthesia considerations for Minimal access cardiac surgery review of 93 cases – Dr.Isha Samadhiya"},
            {"text": "Basic Life Support Course orientation course & Code Blue Protocol was conducted by Shri. Mahadevan & Shri Shravan Kumar to paramedical staff, Sevadal"},
            {"text": "Training Program of First AID &CPR, TO nss students of Maharani College dated 16th& 17thSeptember 2017 as part of Disaster management program conducted at Mysore, Mr..ShravanKumar attended as faculty.", "year": "2017"},
            {"text": "Trainers training program for disaster management team at Brindavan, Dr Kolli S. Chalam dated 10th& 11th June 2017", "year": "2017"},
          ],
        },
        { title:"Other Significant Achievements", count:10,
          entries:[
            {"text": "Kolli S. Chalam serves as member Board of Studies - AHS, RGUHS"},
            {"text": "FIACTA examiner for IACTA fellowships at Fortis hospitals, Delhi in 2019 and Jayadeva institute of cardiological sciences and research, Bangalore in 2020.", "year": "2020"},
            {"text": "Kolli S. Chalam had served as External Examiner for Rajiv Gandhi University of Health Science (RGUHS) Fellowships in Cardiac Anesthesia held at Narayana Hrudayala."},
            {"text": "Kolli S. Chalam, Examiner for fellowship in cardiovascular anaesthesia under Indian college of Anaesthesiologists (ICA) held on 17th June 2018 at Narayana Institute of Cardiac Sciences (NICS), Narayana health city.", "year": "2018"},
            {"text": "Kolli S. Chalam served as External Appraiser for National Board of Examination 16.4.2015 at Kochi, Kerala.", "year": "2015"},
            {"text": "Served as member of scientific committee of Indian Society of Neuro Anesthesiology& Critical Care (ISNACC), an international conference, held at NIMHANS, Bangalore in February 2016", "year": "2016"},
            {"text": "Kolli S. Chalam- peer reviewer of Indian Journal Anesthesiology (IJA), and Member of board of studies & senior faculty of RGUHS and NBE."},
          ],
          subgroups:[
            { title:"FELICITATION BY ISA BANGALORE CITY BRANCH ON WORLD ANAESTHESIA DAY 16TH OCT 2017", entries:[
              {"text": "Dr Kolli S. Chalam was felicitated by MLA malleswaram as chief guest, IG, Director of NIMHANS along with ISA Executive body along with 300 anaesthesiologists in the banquet hall of Lalit Ashok hotel on the occasion of world anaesthesia day felicitated for academic achievements."},
            ] },
            { title:"NBE PRACTICAL EXAMINATION CENTRE", entries:[
              {"text": "Carried DNB final practical examinations for 3 days each time in May 2017 & Nov 2017, 2018, 2019, and 2020.", "year": "2020"},
              {"text": "FAT of NBE: Work Place Based Clinical Assessment of Formative Assessment 2018 by NBE was conducted on 23-02-2019 at SSSIHMS, Bengaluru.", "year": "2019"},
            ] },
          ],
        },
      ] }
  ]
};

})();
